### PR TITLE
Update z3

### PR DESCRIPTION
**Pull request by jurajsic**
Uptade base z3 to v4.12.2

### CODE REVIEW

**Comment by jurajsic** [comment]
Results:
```
# of formulae: 100031
###################################################################################
####                                   Table 1                                 ####
###################################################################################
| method                     |   max |    mean |   median |   std. dev |   TO+MO+ERR |   unknowns |
|----------------------------|-------|---------|----------|------------|-------------|------------|
| z3-noodler-1ba1904-40ca1cd |   132 | 7.04448 |     0.03 |    28.477  |        4307 |       8287 |
| cvc5-1.0.8                 |   132 | 2.81598 |     0.02 |    17.993  |        1772 |          2 |
| z3-4.12.2                  |   132 | 5.2186  |     0.04 |    23.1857 |        2857 |        213 |
| z3str4                     |   132 | 2.3607  |     0.02 |    15.8903 |        1380 |       1385 |
| z3-noodler-0ae38ae-40ca1cd |   132 | 7.04192 |     0.03 |    28.5098 |        4317 |       8291 |
```
image
image
image

**Comment by vhavlena** [comment]
Great! Is it with the newest mata?

**Comment by jurajsic** [comment]
Not yet, I want to run it after merging this.

**Comment by jurajsic** [comment]
The table is wrong, the times are broken, this is the correct version:
```
# of formulae: 100031
###################################################################################
####                                   Table 1                                 ####
###################################################################################
| method                     |    max |     mean |   median |   std. dev |   TO+MO+ERR |   unknowns |
|----------------------------|--------|----------|----------|------------|-------------|------------|
| z3-noodler-1ba1904-40ca1cd | 119.58 | 0.889365 |     0.03 |    6.62393 |        4307 |       8287 |
| cvc5-1.0.8                 | 119.36 | 0.485156 |     0.02 |    4.81569 |        1772 |          2 |
| z3-4.12.2                  | 119.29 | 1.48289  |     0.04 |    8.11434 |        2857 |        213 |
| z3str4                     | 118.44 | 0.519939 |     0.02 |    3.77544 |        1380 |       1385 |
| z3-noodler-0ae38ae-40ca1cd | 119.83 | 0.871344 |     0.03 |    6.61873 |        4317 |       8291 |
```

**Review by Adda0 — COMMENTED** [review]
LGTM.

**Pull request merged**
