### PR TITLE
Turn on reduction for noodlification

### PR DESCRIPTION
**Pull request by jurajsic**
This PR fixes a bug where noodlification did not reduce (nor trim) automata in resulting nooodles.

Needs to be benchmarked, it is possible that simulation might slow it down, or that we should just turn on trimming.

### CODE REVIEW

**Review by vhavlena — APPROVED** [review]

**Comment by vhavlena** [comment]
Maybe the simulation reduction will be too expensive. We could add option "trim" to do just the trimming. But we will see after the results.

**Review by Adda0 — APPROVED** [review]
I would not merge until the results show that there is no significant slowdown. If there is, I would go with the suggested trim instead and merge only the trim.

**Comment by vhavlena** [comment]
I suggest first to finish and merge the PR #104 and then try the effect of the noodle reduction.

**Comment by vhavlena** [comment]
The results (`z3-noodler-feada45-a57f582` is the PR version, `z3-noodler-1482571-a57f582` is the `pyex-opt` version -- NOT devel)
image

```
# of formulae: 82972
###################################################################################
####                                   Table 1                                 ####
###################################################################################
| method                     |    max |     mean |   median |   std. dev |   TO+MO+ERR |   unknowns |
|----------------------------|--------|----------|----------|------------|-------------|------------|
| z3-noodler-feada45-a57f582 | 116.1  | 0.494545 |     0.02 |    3.67665 |        2198 |       2011 |
| cvc5-1.0.8                 | 119.36 | 0.515113 |     0.02 |    5.2351  |        1723 |          2 |
| z3-4.12.2                  | 119.29 | 1.49018  |     0.04 |    8.17615 |        2623 |        123 |
| z3-noodler-1482571-a57f582 | 115.42 | 0.463528 |     0.02 |    3.42857 |        2465 |       2098 |
```

- the version `z3-noodler-1482571-a57f582` lacks some optimisations currently in devel (hard equations, replace_re, lex ordering), the improvement of this PR is not caused only by the noodle reduction. Ignore `woorpje`.
- it seems there is some positive effect (e.g., on kaluza we have 80 TOs less now)

**Comment by vhavlena** [comment]
Should I merge the PR?

**Comment by Adda0** [comment]
I would merge the PR.

**Pull request merged**
