### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by vhavlena**
This PR fixes:

- handling of unsupported predicates
- relevancy propagation for regexes
- predicate fixing

### CODE REVIEW

**Comment by vhavlena** [comment]
@jurajsic Could you please start running all benchmarks on this branch? The changes could possibly introduce new errors.

**Comment by vhavlena** [comment]
@jurajsic Can I merge it, or are there still tests running?

**Comment by Adda0** [comment]
We have to resolve the conflicts at least.

**Comment by jurajsic** [comment]
There is still one problematic instance, `QF_SLIA/20230327-stringfuzz-lu/transformed/z3str2/regex-046-unsat-multiply-translate-fuzz.smt2`, I am trying to debug it now.

**Comment by vhavlena** [comment]
What is wrong with this instance? I am getting unsat.

**Pull request merged**
