### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by vhavlena**
Some fixes

### CODE REVIEW

**Comment by vhavlena** [comment]
@jurajsic Can I merge the branch or are there still some issues?

**Comment by jurajsic** [comment]
I am still running some of the benchmarks, do we want to wait? If I won't run pyex, it should finish today, if I run pyex too, it will take longer, probably until Friday.

**Comment by vhavlena** [comment]
We can wait. I guess we are not in a hurry right now

**Comment by jurajsic** [comment]
I run it on all benchmarks, we return `unsat` for `QF_SLIA/20180523-Reynolds/pyex/peterc-pyex-doc-cav17-zz/httplib2/httplib2-entry-disposition/7aee001e41a9f96fa4fa78cd019b0c108787f769a87b90b27bcfd28a.smt2` while cvc5 and Z3 return `sat`. Problem is that it returns `sat` if I run it on mac, so it needs to be debugged on linux.

**Comment by vhavlena** [comment]
Ok then. I guess we want to fix it before the merge, right?

**Comment by jurajsic** [comment]
I think we can merge, I cannot reproduce the error, even on the server. I think it was caused by updating Mata and I do not know which version of Mata I used when the error occurred.

**Pull request merged**
