### PR TITLE
Collecting statistics

### PR DESCRIPTION
**Pull request by vhavlena**
This PR utilizes Z3's mechanism for collecting statistics in the Noodler string theory (invoked by `-st`). So-far a counter for each decision procedure is provided + number of solved cases by purely preprocessing.

### CODE REVIEW

**Comment by vhavlena** [comment]
@jurajsic Any more ideas what to include to the statistics?

**Comment by jurajsic** [comment]
I would add something for decision procedures that can fail solving, for example underapproximation. Something like "how many times it did not solve" or something. I think it is the only one that can fail, right?

**Comment by jurajsic** [comment]
Also, on line 245/253, we check if we have UNSAT from init length constraints. I think we can make this another statistic (or a part of "number of times preprocessing solved").

**Comment by vhavlena** [comment]
> Also, on line 245/253, we check if we have UNSAT from init length constraints. I think we can make this another statistic (or a part of "number of times preprocessing solved").

Done (included to the preprocessing counter)

**Comment by vhavlena** [comment]
> I would add something for decision procedures that can fail solving, for example underapproximation. Something like "how many times it did not solve" or something. I think it is the only one that can fail, right?

Done. I distinguished the number of starts and number of finishes for each decision procedure (even though it is not necessary for all of them). It might be interesting to track how precise the suitability checking functions are.

**Pull request merged**
